import { Cairo } from "next/font/google";
import "./globals.css";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="ar"
      className={`${cairo.variable} h-full antialiased`}
      dir="rtl"
    >
      <body>{children}</body>
    </html>
  );
}