import { Cairo } from "next/font/google";
import "./globals.css";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
});

export const metadata = {
  title: "First Next.js App - Mhmd Amr",
  description: "Generated by create next app",
  keywords: "fun, run, sun, gun, hun, pun, lun"
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="ar"
      className={`${cairo.variable} h-full antialiased`}
      dir="rtl"
    >
      <body className="flex justify-center items-center h-dvh flex-col gap-2">{children}</body>
    </html>
  );
}